baseurl = "https://www.notquiteablog.com"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Not Quite a Blog"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#googleAnalytics = "XXX"

[Params]
#  homeTitle = "Not Quite a Blog" # Set a different text for the header on the home page
  subtitle = "A public notebook by writer and philosopher, Dr. Will Buckingham."
  mainSections = ["post","posts"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = false
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Will Buckingham"
  website = "willbuckingham.com"
  email = "will@willbuckingham.com"
  facebook = "willbuckinghamwriter"
  github = "username"
  twitter = "willbuckingham"
  linkedin = "willbuckingham"
  instagram = "willbuckinghamwriter"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3


[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
